-- Create a table for user profiles (Netflix-style profiles within an account)
create table public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Links to Supabase Auth User
  name text not null,
  avatar_id text not null,
  is_kid boolean default false,
  settings jsonb default '{"autoplay": true, "subtitleSize": "medium", "subtitleColor": "white"}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Users can view their own profiles" on public.profiles
  for select using (auth.uid() = user_id);

create policy "Users can insert their own profiles" on public.profiles
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own profiles" on public.profiles
  for update using (auth.uid() = user_id);

create policy "Users can delete their own profiles" on public.profiles
  for delete using (auth.uid() = user_id);

-- Create a table for watchlist (Saved Media)
create table public.watchlist (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null, -- 'movie' or 'tv'
  title text not null,
  poster_path text,
  backdrop_path text,
  overview text,
  vote_average numeric,
  release_date text,
  data jsonb, -- Store full media object for caching
  saved_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(profile_id, tmdb_id, media_type)
);

-- Enable RLS
alter table public.watchlist enable row level security;

-- Policies for watchlist
create policy "Users can view their own profiles' watchlist" on public.watchlist
  for select using (
    exists (
      select 1 from public.profiles
      where profiles.id = watchlist.profile_id
      and profiles.user_id = auth.uid()
    )
  );

create policy "Users can insert into their own profiles' watchlist" on public.watchlist
  for insert with check (
    exists (
      select 1 from public.profiles
      where profiles.id = watchlist.profile_id
      and profiles.user_id = auth.uid()
    )
  );
  
create policy "Users can delete from their own profiles' watchlist" on public.watchlist
  for delete using (
    exists (
      select 1 from public.profiles
      where profiles.id = watchlist.profile_id
      and profiles.user_id = auth.uid()
    )
  );

-- Create a table for history/progress
create table public.history (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null,
  title text not null,
  data jsonb,
  progress jsonb, -- { "watched": 120, "duration": 3600, "percentage": 3, "season": 1, "episode": 1 }
  watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(profile_id, tmdb_id, media_type)
);

-- Enable RLS
alter table public.history enable row level security;

-- Policies for history
create policy "Users can view their own profiles' history" on public.history
  for select using (
    exists (
      select 1 from public.profiles
      where profiles.id = history.profile_id
      and profiles.user_id = auth.uid()
    )
  );

create policy "Users can insert into their own profiles' history" on public.history
  for insert with check (
    exists (
      select 1 from public.profiles
      where profiles.id = history.profile_id
      and profiles.user_id = auth.uid()
    )
  );

create policy "Users can update their own profiles' history" on public.history
  for update using (
    exists (
      select 1 from public.profiles
      where profiles.id = history.profile_id
      and profiles.user_id = auth.uid()
    )
  );
